import type { BookDemo } from './types'

/**
 * 测试夹具《赝品眼》：字段按写台分层契约填满，供纯函数测试使用。
 * 不参与运行时：书库从用户新建开始，不再种子任何演示数据。
 */
export const YANPIN_EYE: BookDemo = {
  id: 'yanpin-eye',
  title: '赝品眼',
  pitch: {
    titles: ['赝品眼'],
    platform: '番茄 / 男频 / 都市异能鉴宝',
    logline: '拍卖行底层学徒，一天只能开三次的鉴真瞳，第三次必看见自己的死局。',
    cheat: '鉴真瞳看见器物层理、修缮、来处残影。',
    cost: '每天三次；第一二次只看物；第三次叠加「与自己有关的死局」；连开三次瞳孔出血。',
    comps: '像鉴宝打脸文的场面，但不像系统面板文；像都市异能，但不写升级清单。',
    emotion: '围观里的冷笑反杀 + 越看越像自己要死。',
    hooks: [
      '夜场当众揭「北宋官窑」是喷枪货',
      '被逼签字时用鉴定规则把场子按住',
      '第三次开瞳看见自己死在同一拍场',
    ],
    firstThree: {
      ch1: '羞辱场面 + 金线一闪（只露角）',
      ch2: '第一次开瞳 + 规则落地 + 盟友按住他',
      ch3: '反打完成 + 冲突拖出拍场 + 旧门有人',
    },
    forbiddenBook: '鉴宝说明书，或无代价开挂文。',
  },
  canon: {
    platform: '番茄 / 男频 / 都市异能鉴宝',
    pov: '限知沈见真',
    chapterWords: '2000～2500',
    schedule: '日更一章，备稿 3',
    samples: [
      '喷枪走得太匀，底子不像土。',
      '第三次一开，拍场灯比人先死。',
      '顾晚宁不抬音量：「今晚的鉴定以库房复检为准。」',
    ],
    powerCap: '不能看人心；不能隔空鉴定没看见的东西；第三次必见死局，不可关掉。',
    timeRule: '瞳术按自然日三次，不按「剧情需要」刷新。',
    infoRule: '沈见真只知道自己看见的残影；顾晚宁可以比他多知道一层，但不能一次说完。',
    povRule: '限知沈见真。周少川、顾晚宁的心思只允许用动作和台词泄露。',
    narrativeBan: '禁止系统弹窗；禁止大段文物科普；禁止章末「真正的考验才刚刚开始」。',
    settingBan: '禁止无代价连开；禁止鉴定未亲眼看见的器物。',
    sentenceBan: '禁止平台腔总结句、翻译腔长定语。',
    doneWhen: '有场面、有别人的脸、有一个可见的代价或钩子；没有说明书段落。',
  },
  people: [
    {
      id: 'shen',
      name: '沈见真',
      role: '主角',
      want: '在拍卖行站稳，查清母亲残器从哪来。',
      wound: '母亲留下「不能拍」的残器，第一次开瞳看见自己死在同一厅。',
      secret: '瞳术来自残器。',
      mustNotKnow: '旧门后那人的名字；死局里那张脸是谁。',
      voice: '话少，被逼急了才回嘴。',
      voiceSample: '那你让他们看货。',
      relationToLead: '本人。',
      stateAsOfChapter: 3,
      state: '第3章结束，当众揭穿赝品，被顾晚宁护下，第三次配额未用。',
      volumeArc: '学徒 → 夜场不能被轻易拿掉的人。',
    },
    {
      id: 'zhou',
      name: '周少川',
      role: '对手',
      want: '把夜场变成自己的面子场，并封口。',
      wound: '无。他怕的是局被拆穿，不是良心。',
      secret: '「北宋官窑」是他做的套，为了钓一个不出面的买家。',
      mustNotKnow: '沈见真瞳术的完整规则。',
      voice: '笑着说话，句子里带着「你也配」。',
      voiceSample: '学徒也想过眼？',
      relationToLead: '此刻要当众按住他。',
      stateAsOfChapter: 3,
      state: '当众丢脸，已让人盯上沈见真。',
      volumeArc: '夜场主人 → 必须封口的人。',
    },
    {
      id: 'gu',
      name: '顾晚宁',
      role: '盟友',
      want: '保住瀚海信誉，不把沈见真交出去。',
      wound: '她经手过不该上拍的东西。',
      secret: '认识他母亲，知道残器不该出现在拍品里。',
      mustNotKnow: '死局里那张脸（这一层还不能给她）。',
      voice: '淡、慢、不抬音量。',
      voiceSample: '今晚的鉴定以库房复检为准。',
      relationToLead: '信息优势方，护他但不一次说完。',
      stateAsOfChapter: 3,
      state: '压下当场冲突，约他晚上去库房。',
      volumeArc: '冷淡上司 → 必须和他站在同一库房的人。',
    },
  ],
  rules: [
    {
      id: 'eye',
      name: '鉴真瞳',
      trigger: '必须亲眼看见器物或相关残件。',
      firstTwo: '层理、修缮、来处残影（只看物）。',
      third: '叠加「与自己有关的死局」。',
      quota: '每日三次；连开三次后半天不能再开，瞳孔出血。',
      quotaLeft: '',
      quotaAsOfChapter: 0,
      cannot: '看人心、隔空鉴定、关闭第三次的死局画面。',
      boundTo: '第4章必须第一次主动面对「要不要开第三次」。',
    },
  ],
  places: [
    {
      id: 'hall',
      name: '瀚海夜场',
      job: '当众羞辱与揭赝。',
      whoEnters: '买家、掮客、周少川的人、学徒。',
      hides: '喷枪货、不出面的买家。',
    },
    {
      id: 'vault',
      name: '地下库房',
      job: '把第三次从设定变成今晚的选择。',
      whoEnters: '库房权限者；不速之客已先进不在图纸上的旧门。',
      hides: '母亲残器、旧门后的人。',
    },
  ],
  outline: {
    want: '在拍卖行站稳。',
    need: '查清残器与自己的死局。',
    antagonistWant: '封口、把夜场变成面子场。',
    leverage: '面子、打手、压轴拍品。',
    causality: '因为他用三次机会在赝品堆里活命，所以必须一次次把「看见死」当成交易，才能碰到回收眼睛的人。',
    act1: '把「一日三次、第三次见鬼」亮给读者；主角失去「可以装瞎」的安全感。',
    act2: '对手从当众羞辱升到地下局；主角代价从看货升到看局。',
    act3: '兑现谁在回收能看见死的眼睛；不能新开金手指。',
    foreshadows: [
      {
        id: 'F001',
        line: '第三次必见死局',
        plantVolume: '卷1',
        thisVolume: '第4章必须兑现看见',
        closeWhen: '卷1卷末回收那张脸',
        state: 'due',
      },
      {
        id: 'F002',
        line: '顾晚宁认识他母亲',
        plantVolume: '卷1',
        thisVolume: '只揭一层',
        closeWhen: '后续卷',
        state: 'open',
      },
      {
        id: 'F003',
        line: '旧门后有人',
        plantVolume: '卷1第3章',
        thisVolume: '第4章对峙',
        closeWhen: '未收身份',
        state: 'due',
      },
      {
        id: 'F004',
        line: '死局里的脸叫他别回头',
        plantVolume: '卷1第4章',
        thisVolume: '本轮埋',
        closeWhen: '未收',
        state: 'open',
      },
    ],
    volumeUpgrade: [
      '卷1 升：从「会看货」升到「敢开第三次」。',
      '卷2 升：从「看货」升到「看局」（残器来历、地下局）。',
      '卷3 升：从「看局」升到「谁在回收能看见死的眼睛」。',
    ],
  },
  volumes: [
    {
      id: 'vol-1',
      title: '卷一 · 夜场',
      question: '沈见真能不能从学徒变成夜场拿不走的人，同时把「第三次」从设定变成选择。',
      antagonist: '周少川用面子和打手封口；旧门后的人用残器逼他开第三眼。',
      rulePressure: '第三次配额必须被逼到台前。',
      campaigns: [
        {
          id: 'unit-a',
          name: '夜场翻盘',
          win: '当众揭赝，没被当场签走',
          inState: '底层学徒',
          outState: '当众揭穿赝品，第三次未用',
        },
        {
          id: 'unit-b',
          name: '库房死局',
          win: '第一次主动面对第三次，换到死局里的那张脸',
          inState: '第三次配额未用',
          outState: '配额用尽，看见死局',
        },
        {
          id: 'unit-c',
          name: '残器入图录',
          win: '压轴拍品是母亲残器，他不能装没看见',
          inState: '知道残器不该出现',
          outState: '不能再装瞎',
        },
      ],
      mustPay: ['当众揭赝', '被逼签字反打', '看见自己的死'],
      mustNotPay: ['那张脸的身份', '残器完整来历'],
      slap: '第1～3章 · 周少川 · 凭鉴定规则',
      climax: '库房 · 用掉第三次 · 瞳孔见血',
      endChange: '沈见真不再是可以被当场签走的学徒；F001 看见已兑现、身份未收。',
      readerKnows: '第三次必见死局（第1章已预告）',
      leadDoesNot: '旧门后是谁',
      allyKnows: '残器不该出现，但她不会一次说完',
    },
  ],
  units: [
    {
      id: 'unit-a',
      volumeId: 'vol-1',
      name: '夜场翻盘',
      chapters: '1–3',
      campaign: '当众揭「北宋官窑」是喷枪货，且没被当场签走。',
      win: '当众揭赝，没被当场签走。',
      antagonistMove: '周少川用场面和签字逼他认栽。',
      spent: '第一次开瞳配额。',
      infoPlan: '第1章露金线一角；第2章规则落地；第3章拖出拍场。',
      endHook: '旧门有人。',
      peopleChange: '周少川不能再维持「学徒也配」的轻慢。',
    },
    {
      id: 'unit-b',
      volumeId: 'vol-1',
      name: '库房死局',
      chapters: '4–8',
      campaign: '不速之客逼他当场开第三眼，否则砸残器。',
      win: '他开了第三次，看见死局，且残器没被砸。',
      antagonistMove: '以砸残器逼开瞳。',
      spent: '第三次配额。',
      infoPlan: '第4章给那张脸一句台词；第6–7章给残器与母亲一层关系；第8章把「回头」变成禁令。',
      endHook: '死局里的那张脸在现实里出现过一次侧影。',
      peopleChange: '沈见真不能再把第三次当设定。',
    },
    {
      id: 'unit-c',
      volumeId: 'vol-1',
      name: '残器入图录',
      chapters: '9–？',
      campaign: '压轴拍品是母亲残器。',
      win: '他不能装没看见。',
      antagonistMove: '把残器写进图录，逼他上台。',
      spent: '关系与秘密。',
      infoPlan: '只揭残器不该出现，不给来历。',
      endHook: '图录页上的编号与残器吻合。',
      peopleChange: '顾晚宁不能再只「护」不「说」。',
    },
  ],
  chapters: [
    {
      id: 'ch-1',
      no: 1,
      title: '金线一闪',
      unitId: 'unit-a',
      job: '推进',
      openHook: '夜场灯下，学徒被当众按在拍品前。',
      goal: '没被当场轰出去。',
      resistance: '周少川的面子场。',
      turn: '他看见釉面下一闪金线。',
      pleasure: '羞辱里只露一角金手指。',
      infoGive: '这双眼睛不对。',
      infoForbid: '完整规则。',
      cast: ['shen', 'zhou', 'hall'],
      plant: 'F001 预告',
      press: '',
      close: '',
      endHookKind: '悬念',
      endHook: '金线一闪，像有人在釉面下眨眼。',
      words: '开场 400 / 羞辱 1200 / 金线 500',
      mood: '压 → 冷',
      platform: 'tomato',
    },
    {
      id: 'ch-2',
      no: 2,
      title: '第一次开瞳',
      unitId: 'unit-a',
      job: '兑现',
      openHook: '库房灯亮，顾晚宁按住他的手腕。',
      goal: '第一次开瞳看清喷枪货。',
      resistance: '他不敢在人面前眨眼。',
      turn: '规则落地：一日三次。',
      pleasure: '第一次看见层理。',
      infoGive: '第一二次只看物。',
      infoForbid: '第三次死局画面。',
      cast: ['shen', 'gu', 'eye'],
      plant: '',
      press: 'F001',
      close: '',
      endHookKind: '信息差',
      endHook: '顾晚宁说：今晚别开第三次。',
      words: '开场 300 / 开瞳 1500 / 规则 600',
      mood: '冷 → 压',
      platform: 'tomato',
    },
    {
      id: 'ch-3',
      no: 3,
      title: '把场子按住',
      unitId: 'unit-a',
      job: '翻盘',
      openHook: '签字笔递到他手上。',
      goal: '用鉴定规则反打，不当场签走。',
      resistance: '周少川要他认栽。',
      turn: '「那你让他们看货。」',
      pleasure: '当众揭喷枪货。',
      infoGive: '冲突拖出拍场。',
      infoForbid: '旧门之人的名字。',
      cast: ['shen', 'zhou', 'gu', 'hall'],
      plant: 'F003',
      press: '',
      close: '',
      endHookKind: '危机',
      endHook: '旧门半开，有人先到。',
      words: '开场 300 / 反打 1600 / 旧门 400',
      mood: '压 → 爆 → 悬',
      platform: 'tomato',
    },
    {
      id: 'ch-4',
      no: 4,
      title: '第三次还没用',
      unitId: 'unit-b',
      job: '兑现',
      openHook: '旧门半开，手电先照到残器，再照到一个不该在图纸上的人。',
      goal: '活着把残器留在库房，并决定开不开第三眼。',
      resistance: '不速之客以砸残器逼他当场开瞳。',
      turn: '顾晚宁要拦，对方说「她也护不住第三次」。',
      pleasure: '无碾压。本章的爽是「他看清自己会死在哪」，属于冷爽。',
      infoGive: '死局里那张脸叫他「见真」，并说「你不该回头」。',
      infoForbid: '那张脸的身份；瞳术来源的完整故事。',
      cast: ['shen', 'gu', 'vault', 'eye'],
      plant: 'F004',
      press: 'F001、F003',
      close: '',
      endHookKind: '选择',
      endHook: '死局里的脸对他说完那句，现实里旧门后的人问：「看清了吗？」',
      words: '开场 400 / 对峙 1400 / 开瞳与钩 700',
      mood: '冷 → 压 → 更冷 → 悬',
      platform: 'tomato',
    },
    {
      id: 'ch-5',
      no: 5,
      title: '看清了吗',
      unitId: 'unit-b',
      job: '推进',
      openHook: '',
      goal: '',
      resistance: '',
      turn: '',
      pleasure: '',
      infoGive: '',
      infoForbid: '',
      cast: [],
      plant: '',
      press: '',
      close: '',
      endHookKind: '',
      endHook: '',
      words: '',
      mood: '',
      platform: 'tomato',
      locked: true,
      lockReason: '第4章入卷尚未采纳，不准开下一章。',
    },
  ],
  beatsByChapter: {
    'ch-1': [
      {
        id: 'c1b1',
        title: '按住',
        scene: '夜场灯、拍品、围观。',
        job: '把学徒按在拍品前，让羞辱成为既成事实。',
        dialogue: '周少川：「学徒也想过眼？」沈见真不解释。',
        info: '这双眼睛不对；不给规则。',
        mood: '压。',
        land: '围观把路封死。',
      },
      {
        id: 'c1b2',
        title: '金线',
        scene: '釉面、喷枪痕、一闪。',
        job: '只露金手指一角。',
        dialogue: '无。他没眨眼。',
        info: '釉面下有金线；禁止完整规则。',
        mood: '压 → 冷。',
        land: '金线一闪，像有人在釉面下眨眼。',
      },
      {
        id: 'c1b3',
        title: '散场',
        scene: '灯还亮，人开始让。',
        job: '把钩子留在散场，不总结。',
        dialogue: '无。',
        info: 'F001 预告：第三次必见鬼，只露角。',
        mood: '冷。',
        land: '他听见自己心跳，比拍槌慢半拍。',
      },
    ],
    'ch-2': [
      {
        id: 'c2b1',
        title: '按腕',
        scene: '库房灯、编号、顾晚宁的手。',
        job: '把第一次开瞳从私下变成有人按住。',
        dialogue: '顾晚宁：「今晚别开第三次。」',
        info: '她比他多知道一层，不说完。',
        mood: '冷。',
        land: '手腕被按住。',
      },
      {
        id: 'c2b2',
        title: '开瞳',
        scene: '喷枪货近距。',
        job: '规则落地：一日三次，第一二次只看物。',
        dialogue: '沈见真：「那你让他们看货。」——还没说，先看。',
        info: '层理、修缮；禁止死局画面。',
        mood: '冷 → 压。',
        land: '他看见喷枪走得太匀。',
      },
      {
        id: 'c2b3',
        title: '配额',
        scene: '同一盏库房灯。',
        job: '把代价变成今晚的禁令。',
        dialogue: '顾晚宁重复：「别开第三次。」',
        info: '配额按自然日；不刷新。',
        mood: '压。',
        land: '第三次还在。',
      },
    ],
    'ch-3': [
      {
        id: 'c3b1',
        title: '签字',
        scene: '拍场、笔、围观。',
        job: '把认栽变成必须当面完成的动作。',
        dialogue: '周少川把笔递过来，句子里带着「你也配」。',
        info: '面子场要封口。',
        mood: '压。',
        land: '笔尖对着他的名字。',
      },
      {
        id: 'c3b2',
        title: '反打',
        scene: '同一拍场，货被推到灯下。',
        job: '用鉴定规则按住场子，不当场签走。',
        dialogue: '沈见真：「那你让他们看货。」',
        info: '喷枪货当众揭穿；禁止旧门之名。',
        mood: '压 → 爆。',
        land: '围观先乱，周少川的笑断了。',
      },
      {
        id: 'c3b3',
        title: '旧门',
        scene: '散场通道、半开旧门。',
        job: '把冲突拖出拍场，埋 F003。',
        dialogue: '无名字。只有门缝里的呼吸。',
        info: '有人先到；禁止身份。',
        mood: '爆 → 悬。',
        land: '旧门半开，有人先到。',
      },
    ],
    'ch-4': [
      {
        id: 'b1',
        title: '旧门',
        scene: '地下库房铁架、编号贴纸、半开旧门、手电。',
        job: '让「有人先到」成为既成事实。',
        dialogue: '顾晚宁只说「有人先到了。」',
        info: '这人能进不在图纸上的门；不给名字。',
        mood: '散场后的冷 → 警。',
        land: '手电从残器移到沈见真脸上。',
      },
      {
        id: 'b2',
        title: '逼开',
        scene: '残器、三人距离、恒温风。',
        job: '把「第三次还没用」从配额变成选择。',
        dialogue: '对方逼他开第三眼，否则砸器；沈见真不得解释瞳术。',
        info: '对方知道他眼睛有问题，但不知道完整规则。',
        mood: '压。',
        land: '他抬眼。',
      },
      {
        id: 'b3',
        title: '死局',
        scene: '现实库房叠死局拍场。',
        job: '兑现 F001，埋 F004。',
        dialogue: '死局里的脸只给一句「见真，你不该回头。」',
        info: '脸认识他；禁止身份。',
        mood: '冷悬。',
        land: '现实里的人问「看清了吗？」',
      },
    ],
  },
  drafts: [
    {
      chapterId: 'ch-1',
      accepted: true,
      beats: [
        {
          beatId: 'c1b1',
          body: '夜场灯把他按在拍品前。围观的呼吸比空调还近。\n周少川笑着问：「学徒也想过眼？」',
        },
        {
          beatId: 'c1b2',
          body: '喷枪走得太匀，底子不像土。釉面下一闪金线，像有人在眨眼。\n沈见真没有眨眼。',
        },
        {
          beatId: 'c1b3',
          body: '人开始让。灯还亮。他听见自己心跳，比拍槌慢半拍。',
        },
      ],
    },
    {
      chapterId: 'ch-2',
      accepted: true,
      beats: [
        {
          beatId: 'c2b1',
          body: '库房灯亮。顾晚宁按住他的手腕，音量不抬：「今晚别开第三次。」',
        },
        {
          beatId: 'c2b2',
          body: '他看见层理。第一二次只看物。喷枪货的修缮痕迹像一张不肯改口的嘴。',
        },
        {
          beatId: 'c2b3',
          body: '配额按自然日。第三次还在。她只重复那一句，没有把后面的话说完。',
        },
      ],
    },
    {
      chapterId: 'ch-3',
      accepted: true,
      beats: [
        {
          beatId: 'c3b1',
          body: '签字笔递到他手上。周少川的句子里带着「你也配」。',
        },
        {
          beatId: 'c3b2',
          body: '沈见真说：「那你让他们看货。」\n喷枪货被推到灯下。围观先乱。',
        },
        {
          beatId: 'c3b3',
          body: '冲突被拖出拍场。旧门只开一条缝，缝里先是呼吸，再是不该出现的鞋尖。',
        },
      ],
    },
    {
      chapterId: 'ch-4',
      accepted: false,
      beats: [
        {
          beatId: 'b1',
          body: '铁架上的编号贴纸被手电刮过，白得刺眼。旧门只开一条缝，缝里先是残器，再是一只不该出现在图纸上的鞋尖。\n顾晚宁把音量压住：「有人先到了。」',
        },
        {
          beatId: 'b2',
          body: '恒温风从残器边擦过去。那人把锤子搁在木匣沿上，笑得很轻：「开第三眼。否则我砸。」\n顾晚宁要拦。他说：「她也护不住第三次。」\n沈见真没有解释瞳术。他只是抬眼。',
        },
        {
          beatId: 'b3',
          body: '库房灯还在，拍场灯已经比人先死。那张脸隔着死局叫他：「见真，你不该回头。」\n现实里，旧门后的人问：「看清了吗？」',
        },
      ],
    },
  ],
  reviews: [
    {
      chapterId: 'ch-1',
      openHookOk: '前 300 字：夜场灯、拍品、学徒被按住。',
      goalOk: '没被当场轰出去。',
      endHookOk: '金线一闪，不是总结句。',
      voiceLeak: '无。他未解释眼睛。',
      forbiddenKnow: '完整规则未给。',
      cheatAbuse: '只露一角，未开瞳。',
      dueSeen: 'F001 只预告。',
      unnumbered: '无。',
      states: ['沈见真：当众受辱，看见金线一角。', '周少川：面子场还在。'],
      foreshadow: ['F001：预告，未兑现。'],
      summary80: '夜场学徒被按在拍品前。釉面金线一闪。',
      adopted: true,
    },
    {
      chapterId: 'ch-2',
      openHookOk: '库房灯、按腕。',
      goalOk: '第一次开瞳看清喷枪货。',
      endHookOk: '「今晚别开第三次。」',
      voiceLeak: '无。',
      forbiddenKnow: '第三次死局画面未给。',
      cheatAbuse: '第一次开瞳有配额。',
      dueSeen: 'F001 被催，未兑现看见。',
      unnumbered: '无。',
      states: ['沈见真：规则落地，第三次未用。', '顾晚宁：按住他，不一次说完。'],
      foreshadow: ['F001：催。'],
      summary80: '第一次开瞳。一日三次落地。顾晚宁不许他开第三次。',
      adopted: true,
    },
    {
      chapterId: 'ch-3',
      openHookOk: '签字笔递到手上。',
      goalOk: '不当场签走，当众揭赝。',
      endHookOk: '旧门半开，有人先到。',
      voiceLeak: '无。',
      forbiddenKnow: '旧门之人未给名。',
      cheatAbuse: '未新开金手指。',
      dueSeen: 'F003 已埋。',
      unnumbered: '无。',
      states: [
        '沈见真：当众揭赝，没被签走。',
        '周少川：当场丢脸。',
        '顾晚宁：压下冲突，约库房。',
      ],
      foreshadow: ['F003：已埋。'],
      summary80: '他用鉴定规则把场子按住。旧门有人先到。',
      adopted: true,
    },
    {
      chapterId: 'ch-4',
      openHookOk: '前 300 字：旧门、残器、不该在图纸上的人。',
      goalOk: '残器没被砸；他开了第三眼。',
      endHookOk: '「看清了吗？」不是总结句。',
      voiceLeak: '无。沈见真未解释瞳术。',
      forbiddenKnow: '那张脸身份未给；来历未说完。',
      cheatAbuse: '第三次有代价：见血（入卷）。未隔空、未看心。',
      dueSeen: 'F001 被看见；身份未收。',
      unnumbered: '无',
      states: [
        '沈见真：第一次主动面对第三次，看见死局，听见「别回头」；配额用尽，瞳孔见血。',
        '顾晚宁：没能阻止开瞳，知道旧门后的人比她更清楚残器。',
        '不速之客：仍未给名，但确认沈见真开了第三眼。',
      ],
      foreshadow: [
        'F001：due → 本轮兑现「看见」，身份未收，保持 open。',
        'F003：旧门之人从影子变成对峙方。',
        'F004：已埋。',
      ],
      summary80: '库房旧门有人逼开第三眼。沈见真看见自己死在拍场，那张脸叫他别回头。',
      adopted: false,
    },
  ],
}
